version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
      - db

  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./:/var/www/html

  composer:
    image: composer
    volumes:
      - ./:/app
    command: install

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
